# Generated by Django 5.0.4 on 2024-04-09 18:50

import EcommerceApis.Enums.userType
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('user_type', models.IntegerField(choices=[(1, 'SELLER'), (2, 'BUYER')], default=EcommerceApis.Enums.userType.UserType['BUYER'])),
                ('is_active', models.BooleanField(default=True)),
                ('wallet_balance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
