openapi: 3.0.3
info:
  title: Ecommerce APIs
  version: 1.0.0
  description: A Practive Project
paths:
  /users/register:
    post:
      operationId: users_register_create
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - jwtHeaderAuth: []
      - jwtCookieAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email
          maxLength: 254
        password:
          type: string
          writeOnly: true
        user_type:
          allOf:
          - $ref: '#/components/schemas/UserTypeEnum'
          minimum: -2147483648
          maximum: 2147483647
        is_active:
          type: boolean
        wallet_balance:
          type: number
          format: double
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - email
      - first_name
      - id
      - last_name
      - password
      - updated_at
      - wallet_balance
    UserTypeEnum:
      enum:
      - 1
      - 2
      type: integer
      description: |-
        * `1` - SELLER
        * `2` - BUYER
  securitySchemes:
    jwtCookieAuth:
      type: apiKey
      in: cookie
      name: my-app-auth
    jwtHeaderAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
